### ISSUE TITLE
文件浏览，浏览不在线的的主机文件，后端程序挂掉了

### ISSUE THREAD

**Issue by lixin59** [ssbeatty/oms#12]
bug复现操作:
 1.进入文件浏览界面，选择一个不在线的主机，点击浏览，过一会，后端程序会挂掉。

建议：
  1.浏览不在线的主机应该有错误提示信息，“无法连接目标主机”

**Comment by ssbeatty** [comment]
fixed 1af787dceca7180af09eb33868ba540b66afe6d3
