### ISSUE TITLE
新增主机时地址不支持域名

### ISSUE THREAD

**Issue by mostcute** [ssbeatty/oms#16]
![image](https://user-images.githubusercontent.com/23225426/189034276-c07095f4-430c-44e7-bb55-673e1644cdb4.png)

我觉得很有必要支持一下

**Comment by ssbeatty** [comment]
fix b1b5c670fdd4d243bf4b8dc7b5c7d9b823557898

**Comment by mostcute** [comment]
`Addr         string `form:"addr" binding:"required,ip_addr"``
方案 1：这里把ip_addr去掉   结果，可以支持域名，但是失去了基本的校验
方案 2:   自定义这个结构体的校验方法， 结果，对比方案一稍显麻烦

哪一种更合适呢，不知道 validator语法支不支持多种类型或判断，但是类型里好像没有域名校验

**Comment by mostcute** [comment]
这修的也太快了吧，老板专业啊
