### ISSUE TITLE
主机监控页面无法使用

### ISSUE THREAD

**Issue by mostcute** [ssbeatty/oms#17]
![image](https://user-images.githubusercontent.com/23225426/189044453-23b5c7bc-f9c5-40db-afeb-d6e2d709abb6.png)

不知道什么原因，一开始我以为是我测试机是lxc的原因，后来换了华为云还是不行

**Comment by ssbeatty** [comment]
![image](https://user-images.githubusercontent.com/41351315/189088884-e7aa3015-fa27-4ca6-92ef-366c7a67c674.png)

麻烦提供下这个payload

**Comment by ssbeatty** [comment]
麻烦再提供下后端日志输出，估计哪里报错了

**Comment by mostcute** [comment]
未见明显报错
![image](https://user-images.githubusercontent.com/23225426/189106821-5763beb7-0c45-4ea7-9c65-5a3f7227c7a4.png)

**Comment by mostcute** [comment]
这个cancel是上一条的取消吧

**Comment by mostcute** [comment]
需要提供我编译出来的二进制试下吗，代码是dev最新，支持域名那个

**Comment by ssbeatty** [comment]
应该不需要 我先调试下吧

**Comment by mostcute** [comment]
有什么进展吗

**Comment by ssbeatty** [comment]
没复现出来，可以帮忙调试下吗 看看是哪里报错的

**Comment by mostcute** [comment]
好的，需要我做什么

**Comment by mostcute** [comment]
跟启动方式有关吗，我是直接./oms启动的，没有任何参数和指定配置

**Comment by ssbeatty** [comment]
![image](https://user-images.githubusercontent.com/41351315/189274182-51dac3aa-6a73-44c7-8661-6b1ca3c01666.png)
启动方式没关系的，你可以用goland调试下这段代码，看看为啥这个status是空的

**Comment by mostcute** [comment]
我打印了几个地方，都是有值的
![image](https://user-images.githubusercontent.com/23225426/189304738-f17730b4-cd50-4894-9edc-04085a301438.png)

![image](https://user-images.githubusercontent.com/23225426/189304872-924daed5-f4af-477e-a3c9-f3b33c8fe0d8.png)

**Comment by mostcute** [comment]
找到问题了

![image](https://user-images.githubusercontent.com/23225426/189305611-fe99f821-d749-4342-bd9b-f68d6bd057ac.png)

![image](https://user-images.githubusercontent.com/23225426/189305688-58e2a363-2134-419c-a58b-ac19bbe070d6.png)

应该是一个值拿不到返回NaN 无法序列化，你这里忽略了这个错误

**Comment by ssbeatty** [comment]
可以看下是哪个结构体的哪个字段吗，我修复一下，十分感谢

**Comment by ssbeatty** [comment]
可能是因为除数为0 无穷大了

**Comment by mostcute** [comment]
出错在这里，发生了 0/0
![image](https://user-images.githubusercontent.com/23225426/189306742-6d397bc7-a38b-4b56-890b-77e6444c7b32.png)

**Comment by ssbeatty** [comment]
fixed 13d75ced4fd9d867a3f0440619cfa03250487041

**Comment by mostcute** [comment]
主机内存数值问题，我认为不应该把pagecache算上
![image](https://user-images.githubusercontent.com/23225426/189318054-ab04feda-0596-4fac-b72a-c19b54674679.png)

**Comment by mostcute** [comment]
![image](https://user-images.githubusercontent.com/23225426/189325075-7df2662e-5912-4ba4-bcaf-d73b7d95e96d.png)
![image](https://user-images.githubusercontent.com/23225426/189325137-e4b79105-88f5-48f1-8a0d-f0112f612e0b.png)
这样会不会好一点

**Comment by ssbeatty** [comment]
去掉pagecache是会好看点，好的我改下 你有兴趣的话也可以提交一些pr

**Comment by mostcute** [comment]
我改好了，我提交一下
