### ISSUE TITLE
vendor 目前有什么必要性吗

### ISSUE THREAD

**Issue by mostcute** [ssbeatty/oms#19]
发现工程内使用了vendor，请问有什么必要性吗，修改了一些第三方包？

**Comment by ssbeatty** [comment]
这个主要是担心有可能使用的第三方包停止维护后拉不到，那样修改起来可能会比较麻烦

**Comment by mostcute** [comment]
好吧

就是vendor机制我有两三年没用了，不是太了解新增依赖和更新依赖的方法，方便往文档里加一点说明吗，方便之后其他人维护这个项目

还有go 的embed特性可以用起来了，提升这个项目的快速开始的体验

https://github.com/ssbeatty/oms/pull/20 这个我已经调试过了

**Comment by ssbeatty** [comment]
好的
