### ISSUE TITLE
组内两台机器，按组执行命令只返回一台机器执行结果

### ISSUE THREAD

**Issue by mostcute** [ssbeatty/oms#21]
![image](https://user-images.githubusercontent.com/23225426/192102119-b932bb85-4ccd-4385-8ee9-f0eaa2b416f3.png)
![image](https://user-images.githubusercontent.com/23225426/192102145-a91152d0-b199-41db-a7f0-79dfc72861b9.png)

**Comment by ssbeatty** [comment]
这个是否有日志信息，正常来说两个机器都执行完成后会返回一个信息提示本次命令完毕。如果没返回可能是在连接中或者执行超时了
