### ISSUE TITLE
经常遇到 SQLITE_BUSY

### ISSUE THREAD

**Issue by mostcute** [ssbeatty/oms#23]
![image](https://user-images.githubusercontent.com/23225426/194688488-4f04b770-c3bf-4ca9-b264-646e1f5f5783.png)

**Comment by ssbeatty** [comment]
这个确实是一个比较大的问题，当初为了简单使用了gorm 没有对storage进行好的设计，导致sqlite会有各种问题。现在的想法是使用其他的本地存储引擎比如 https://github.com/asdine/storm 来取代sqlite作为本地存储，但是工作量相对较大，可能需要一定时间

**Comment by mostcute** [comment]
确实工作量太大了
主要还是得想好方向，要不就继续mysql/pg放弃sqllite，要不就选新的单机存储引擎。
不过从我的角度看我非常喜欢不依赖第三方数据库连接的程序，部署简洁没有依赖
