### ISSUE TITLE
新功能建议，多窗口和多文件浏览

### ISSUE THREAD

**Issue by mostcute** [ssbeatty/oms#24]
文件浏览功能包含了文件上传和下载，建议支持tab来支持同时浏览多个服务器
如termius sftp功能
![image](https://user-images.githubusercontent.com/23225426/194688613-f5bfc972-6d32-4898-8d6a-1362c06681b2.png)

ssh 窗口也支持splitview 多窗口以同时监控/操作多台主机 
![image](https://user-images.githubusercontent.com/23225426/194688690-e8bc39da-3eff-4561-ae4c-835bc1df46cd.png)

非常喜欢这套oms系统，可以开放一些开发计划让他更好的继续向前发展

**Comment by lrm929** [comment]
运行之后，浏览器输入  IP+端口 是空白页面，是要加什么么

**Comment by ssbeatty** [comment]
> 运行之后，浏览器输入 IP+端口 是空白页面，是要加什么么

你好，能用cmd运行下发下日志吗
