### ISSUE TITLE
不支持https访问

### ISSUE THREAD

**Issue by sunyue1380** [ssbeatty/oms#25]
使用nginx反代，添加https证书，使用https协议访问时会报如下错误：
![image](https://user-images.githubusercontent.com/6189432/197707959-cc77a762-b033-43d2-a25f-c29a719cc45d.png)

查询了一下网上的解决方案，可以在html添加如下标签：
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />`

我不懂go，所以希望作者能够完善。

再次感谢作者的开源。

**Comment by ssbeatty** [comment]
这个可能是因为前端代码没有做处理 我看一下

**Comment by ssbeatty** [comment]
已处理，我在本地使用nginx测试过了。感谢反馈

**Comment by sunyue1380** [comment]
> 已处理，我在本地使用nginx测试过了。感谢反馈

如果方便的话，能不能尽快在github上发个新的版本呢？由于安全性原因，不支持https的情况下我不敢在外网上部署此程序，谢谢了。

**Comment by ssbeatty** [comment]
刚才发布的v0.7.2是支持的
